app/main/forms.py
# coding=utf-8
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SelectField,\
    SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp
from wtforms import ValidationError
from ..models import Role, User
from flask.ext.pagedown.fields import PageDownField

class EditProfileForm(FlaskForm):
    name = StringField(u'姓名', validators=[Length(1, 64)])
    location = StringField(u'所在地', validators=[Length(1, 64)])
    tel = StringField(u'联系电话', validators=[Length(1, 64)])
    qq = StringField(u'QQ', validators=[Length(1, 64)])
    about_me = TextAreaField(u'关于我')
    submit = SubmitField(u'保存')


class PostFrom(FlaskForm):
    body = TextAreaField(u'你的想法',validators=[DataRequired()])
    submit = SubmitField(u'提交')

app/main/__init__.py
# coding=utf-8
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
# coding=utf-8
from flask import render_template, redirect, url_for, abort, flash, request,\
    current_app, make_response
from flask_login import login_required, current_user
from flask_sqlalchemy import get_debug_queries
import flask
from . import main
from .forms import EditProfileForm,PostFrom
from .. import db
from ..models import Permission, Role, User, Post, Comment



@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html',active=1)


@main.route('/main', methods=['GET', 'POST'])
def main_page():
    form = PostFrom()
    if flask.request.method == 'GET':
        posts = Post.query.order_by(Post.timestamp.desc()).all()
        return render_template('main.html',form=form,posts=posts)
    else:
        if current_user.can(Permission.WRITE) and form.validate():
            post = Post(body=form.body.data,author=current_user._get_current_object())
            db.session.add(post)
            return redirect(url_for('.main_page'))
        else:
            flash(u'您不具有发表的权限')
         #   Role.insert_roles()
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template('main.html', form=form, posts=posts)

@main.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    #page = request.args.get('page', 1, type=int)
    #pagination = user.posts.order_by(Post.timestamp.desc()).paginate(
    #    page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
    #    error_out=False)
    #posts = pagination.items
    # return render_template('user.html', user=user, posts=posts,
    #                      pagination=pagination)
    return render_template('user.html',user = user)


@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if flask.request.method == "GET":
        return render_template('edit_profile.html', form=form,user=current_user)
    else:
        if form.validate():
            current_user.name = form.name.data
            current_user.location = form.location.data
            current_user.about_me = form.about_me.data
            db.session.add(current_user._get_current_object())
            db.session.commit()
            flash(u'个人信息已经更新')
          #  print current_user.location
            return redirect(url_for('.user', username=current_user.username))
        form.name.data = current_user.name
        form.location.data = current_user.location
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form,user=current_user)

app/templates/_index.html
{% block doc -%}
<!DOCTYPE html>
<html lang="en" {% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    {%- endblock metas %}

    {%- block styles %}
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block scripts %}
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

app/templates/base.html
{% extends "_index.html" %}


{%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="qyq" content="smarthome!">
{%- endblock metas %}

{% block styles %}


    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'dist/css/flat-ui.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'css/style.css') }}" >
    <link rel="shortcut icon" href="{{ url_for('static',filename = 'img/favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'css/flaskstyle.css') }}">
{% endblock %}

{% block navbar %}
    <div class="container" >
        <div class="row">
    	<div class="col-md-16">
			<h3 class="text-left text-info">

			</h3>
			<h5>
                 欢迎来到物联网--智能家居博客站!
			</h5>
        </div>
            </div>
	<div  class="row" >
        <div class="col-md-16">
			<ul class="nav nav-pills ">
				<li class=" menuItem {% if active == 1 %}active{% endif %}">
					<a  href="{{ url_for('main.index') }}">首页</a>
				</li>
				<li class=" menuItem {% if active == 2 %}active{% endif %}">
					<a href="{{ url_for('main.main_page') }}">博客</a>
				</li>
                <li class=" menuItem">
					<a id="duck" href="#">产品</a>
				</li>
                <li class=" menuItem">
					<a id="download" href="#">下载</a>
				</li>
                 <li class=" menuItem">
					<a id="common" href="#">联系</a>
				</li>
                <li class=" menuItem">
					<a id="empty" href="#">       </a>
				</li>

                {% if current_user.is_authenticated %}

                     <li class="dropdown pull-right">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown">账户
					    <b class="caret"></b>
				        </a>
                     <ul class="dropdown-menu">
                        <li><a href="{{ url_for('main.user', username=current_user.username) }}">我的信息</a></li>
                         <li class="divider"></li>
                        <li><a href="{{ url_for('auth.logout') }}">我的博客</a></li>
                         <li class="divider"></li>
                        <li><a href="{{ url_for('auth.change_password') }}">修改密码</a></li>
                         <li class="divider"></li>
                        <li><a href="{{ url_for('auth.change_email_request') }}">修改邮箱</a></li>
                        <li class="divider"></li>
                        <li><a href="{{ url_for('auth.logout') }}">登出</a></li>
				    </ul>

                {% else %}

                    <li class="pull-right {% if active == 7 %}active{% endif %}">

                        <a class="glyphicon glyphicon-log-in" href="{{ url_for('auth.login') }}">登录</a>
                    </li>
                    <li class="pull-right">
                        <a class="glyphicon glyphicon-user" href="{{ url_for('auth.register') }}">注册</a>
                    </li>
            {% endif %}
			</ul>
        </div>
    </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
    </div>

    {% block page_content %}
    {% endblock %}
{% endblock %}

{% block scripts %}

    <script src=" {{ url_for('static',filename = 'js/bootstrap.min.js') }}"></script>
<script src=" {{ url_for('static',filename = 'js/jquery.min.js') }}"></script>

<script src="{{ url_for('static',filename = 'dist/js/flat-ui.min.js') }}"></script>
<script src=" {{ url_for('static',filename = 'js/scripts.js') }}"></script>
{{ moment.include_moment() }}
{%- endblock %}

app/templates/download.html
{{% extends "base.html" %}

{% block title %}下载{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}

    {% block title %}编辑信息{% endblock %}


{% block content %}
    {{ super() }}
    <form method="POST">
                {{ form.csrf_token }}
    <div class="container" style="margin-top: 5%;margin-bottom: 5%" >
        <div class="row" style="margin-right: 10%;margin-left: 10%">
            <table class="table">
                <caption>基本信息</caption>
                <tbody>
                    <tr >
                        <td style="padding: 20px">用户账户：</td>
                        <td style="padding: 20px">{{ user.email }}</td>
                    </tr>
                    <tr>
                        <td style="padding: 20px">用户名：</td>
                        <td style="padding: 20px">{{ user.username }}</td>
                    </tr>
                   <tr>
                        <td style="padding: 20px">姓名：</td>
                        <td style="padding: 20px">{{ form.name(class="form-control") }}
                            {% for e in form.name.errors %}
                            <small style="color: red">*{{ e }}</small>
                            {% endfor %}
                        </td>
                    </tr>
                   <tr>
                        <td style="padding: 20px">所在地：</td>
                        <td style="padding: 20px">{{ form.location(class="form-control") }}
                         {% for e in form.location.errors %}
                            <small style="color: red">*{{ e }}</small>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 20px">关于我：</td>
                        <td style="padding: 20px">{{ form.about_me(class="form-control") }}
                            {% for e in form.about_me.errors %}
                            <small style="color: red">*{{ e }}</small>
                            {% endfor %}
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>

        <div class="row" style="margin-top:2%;margin-right: 10%;margin-left: 10%">
            <table class="table">
                <caption>联系方式</caption>
                <tbody>
                    <tr >
                         <td style="padding: 20px">联系电话：</td>
                        <td style="padding: 20px">{{ form.tel(class="form-control") }}
                            {% for e in form.tel.errors %}
                            <small style="color: red">*{{ e }}</small>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 20px">邮箱</td>
                        <td style="padding: 20px">{{ user.email }}</td>
                    </tr>
                   <tr>
                         <td style="padding: 20px">QQ：</td>
                        <td style="padding: 20px">{{ form.qq(class="form-control") }}
                            {% for e in form.qq.errors %}
                            <small style="color: red">*{{ e }}</small>
                            {% endfor %}
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    <div class="row"  style="margin-left: 10%">
         <div class="col-xs-3">
                  {{ form.submit(class="btn btn-block btn-lg btn-default") }}
            </div>
    </div>
    </div>
    </form>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}万物互联{% endblock %}
{% block metas %}
    {{ super() }}
    <meta name="viewport" content="width=1000, initial-scale=1.0, maximum-scale=1.0">
{% endblock %}


{% block content %}
    {{ super() }}
    <div class="container"  >
    <div class="row" >
    <div  class="carousel slide" id="carousel-287345" >
				<ol class="carousel-indicators">
					<li data-slide-to="0" data-target="#carousel-287345">
					</li>
					<li data-slide-to="1" data-target="#carousel-287345" class="active">
					</li>
					<li data-slide-to="2" data-target="#carousel-287345">
					</li>
				</ol>
				<div class="carousel-inner">
					<div class="item">
						<img alt="Carousel Bootstrap First" src= "{{ url_for('static',filename =  'img/1.jpg') }}">
						<div class="carousel-caption">
							<h4>
								互联
							</h4>
							<p>
								互联所有的物体
							</p>
						</div>
					</div>
					<div class="item active">
						<img alt="Carousel Bootstrap Second" src= "{{ url_for('static',filename =  'img/2.jpg') }}">
						<div class="carousel-caption">
							<h4>
								绿色
							</h4>
							<p>
								节能环保
							</p>
						</div>
					</div>
					<div class="item">
						<img alt="Carousel Bootstrap Third" src="{{ url_for('static',filename =  'img/3.jpg') }}">
						<div class="carousel-caption">
							<h4>
								共享
							</h4>
							<p>
								分享生活的点滴
							</p>
						</div>
					</div>
				</div> <a class="left carousel-control" href="#carousel-287345" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-287345" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
			</div>
			<div class="row">
				<div class="col-xs-4">
					<div class="thumbnail">
						<img alt="Bootstrap Thumbnail First" src="http://lorempixel.com/output/people-q-c-600-200-1.jpg">
						<div class="caption">
							<h3>
								发现
							</h3>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
							<p>
								<a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
							</p>
						</div>
					</div>
				</div>
				<div class="col-xs-4">
					<div class="thumbnail">
						<img alt="Bootstrap Thumbnail Second" src="http://lorempixel.com/output/city-q-c-600-200-1.jpg">
						<div class="caption">
							<h3>
								Thumbnail label
							</h3>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
							<p>
								<a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
							</p>
						</div>
					</div>
				</div>
				<div class="col-xs-4">
					<div class="thumbnail">
						<img alt="Bootstrap Thumbnail Third" src="http://lorempixel.com/output/sports-q-c-600-200-1.jpg">
						<div class="caption">
							<h3>
								Thumbnail label
							</h3>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
							<p>
								<a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
							</p>
						</div>
					</div>
				</div>
			</div>
    </div>
        <div class="row">
 <h3 class="demo-panel-title mbl pbl">Samples</h3>
      <div class="row demo-samples">
        <div class="col-xs-4">
          <div class="todo">
            <ul>
              <li class="todo-done">
                <div class="todo-icon fui-user"></div>
                <div class="todo-content">
                  <h4 class="todo-name">
                    Meet <strong>Adrian</strong> at <strong>6pm</strong>
                  </h4>
                  Times Square
                </div>
              </li>
              <li>
                <div class="todo-icon fui-list"></div>
                <div class="todo-content">
                  <h4 class="todo-name">
                    Chat with <strong>V.Kudinov</strong>
                  </h4>
                  Skype conference an 9 am
                </div>
              </li>
              <li>
                <div class="todo-icon fui-eye"></div>
                <div class="todo-content">
                  <h4 class="todo-name">
                    Watch <strong>Iron Man</strong>
                  </h4>
                  1998 Broadway
                </div>
              </li>
                 <li>
                <div class="todo-icon fui-eye"></div>
                <div class="todo-content">
                  <h4 class="todo-name">
                    Watch <strong>Iron Man</strong>
                  </h4>
                  1998 Broadway
                </div>
              </li>
              <li>
                <div class="todo-icon fui-time"></div>
                <div class="todo-content">
                  <h4 class="todo-name">
                    Fix bug on a <strong>Website</strong>
                  </h4>
                  As soon as possible
                </div>
              </li>
            </ul>
          </div><!-- /.todo -->
        </div><!-- /.col-xs-4 -->

        <div class="col-xs-8">
          <video id="my-video" class="video-js" preload="auto" poster="docs/assets/img/video/poster.jpg" data-setup="{}">
            <source src="{{ url_for('static',filename = 'wuzhen.mp4') }}" type="video/mp4">
            <source src="http://iurevych.github.com/Flat-UI-videos/big_buck_bunny.webm" type="video/webm">
          </video>
        </div> <!-- /video -->
      </div>
    </div>
	<div class="row">
		<div class="col-md-4">
			<h2>
				Heading
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Heading
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Heading
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8">
		</div>
		<div class="col-md-4">
			 
			<address>
				 <strong>Twitter, Inc.</strong><br> 795 Folsom Ave, Suite 600<br> San Francisco, CA 94107<br> <abbr title="Phone">P:</abbr> (123) 456-7890
			</address>
		</div>
	</div>

    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static',filename = 'dist/js/vendor/video.js') }}"></script>
    <script src="{{ url_for('static',filename = 'dist/docs/assets/js/application.js') }}"></script>
{% endblock %}

app/templates/main.html
{% extends "base.html" %}

{% block title %}博客{% endblock %}

{% block content %}
    {{ super() }}

    <div class="container">
        <div class="row">
            <form method="POST">
                {{ form.csrf_token }}
                <h6 style="color: #2ecc71">您此时的想法？</h6>
                {{ form.body(class="form-control") }}
                <div class="col-xs-3">
                    {{ form.submit(class="btn btn-block btn-lg btn-default") }}
            </div>
            </form>
        </div>
    <div class="row">
            <ul class="posts">
                {% for post in posts %}
                <li class="post">
                    <div class="profile-thumbnail">
                        <a href="{{ url_for('.user',username=post.author.username) }}">
                            <img class="img-rounded profile-thumbnail" src="">
                        </a>
                    </div>
                    <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
                    <div class="post-author">
                        <a href="{{ url_for('.user',username=post.author.username) }}">
                            {{ post.author.username }}
                        </a>
                    </div>
                    <div class="post-body">{{ post.body }}</div>
                </li>
                {% endfor %}
            </ul>

        </div>
    </div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

    {% block title %}我的信息{% endblock %}


{% block content %}
    {{ super() }}
    <div class="container" style="margin-top: 5%;margin-bottom: 5%" >
        <div class="row" style="margin-right: 10%;margin-left: 10%">
            <table class="table">
                <caption>基本信息</caption>
                <tbody>
                    <tr >
                        <td style="padding: 20px">用户账户：</td>
                        <td style="padding: 20px">{{ user.email }}</td>
                    </tr>
                    <tr>
                        <td style="padding: 20px">用户名：</td>
                        <td style="padding: 20px">{{ user.username }}</td>
                    </tr>
                   <tr>
                        <td style="padding: 20px">姓名：</td>
                        <td style="padding: 20px">{{ user.name }}</td>
                    </tr>
                   <tr>
                        <td style="padding: 20px">所在地：</td>
                        <td style="padding: 20px">{{ user.location }}</td>
                    </tr>
                    <tr>
                        <td style="padding: 20px">关于我：</td>
                        <td style="padding: 20px">{{ user.about_me }}</td>
                    </tr>
                </tbody>
            </table>

        </div>



        <div class="row" style="margin-top:2%;margin-right: 10%;margin-left: 10%">
            <table class="table">
                <caption>联系方式</caption>
                <tbody>
                    <tr >
                        <td style="padding: 20px">联系电话：</td>
                        <td style="padding: 20px"></td>
                    </tr>
                    <tr>
                        <td style="padding: 20px">邮箱</td>
                        <td style="padding: 20px">{{ user.email }}</td>
                    </tr>
                   <tr>
                        <td style="padding: 20px">QQ：</td>
                        <td style="padding: 20px"></td>
                    </tr>
                </tbody>
            </table>

        </div>
        <div class="row"  style="margin-left: 10%">
            <div class="col-xs-3">
                <a class=" btn btn-block btn-lg btn-default" href="{{ url_for('main.edit_profile') }}">编辑</a>
            </div>
    </div>
    </div>
{% endblock %}